# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troupunit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='army',
            name='count',
        ),
        migrations.AlterField(
            model_name='army_party',
            name='unitList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='armylist.Unit'),
        ),
        migrations.DeleteModel(
            name='TroupUnit',
        ),
    ]
