# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0003_auto_20161105_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='unitList',
        ),
        migrations.AddField(
            model_name='unit',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitList', to='armylist.Army'),
        ),
        migrations.AlterField(
            model_name='army_party',
            name='unitList',
            field=models.ManyToManyField(related_name='unitParties', through='armylist.TroupUnit', to='armylist.Unit'),
        ),
        migrations.AlterField(
            model_name='troupunit',
            name='armyParty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TroupsParties', to='armylist.Army_Party'),
        ),
        migrations.AlterField(
            model_name='troupunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unittroups', to='armylist.Unit'),
        ),
    ]
