# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0006_auto_20161107_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
