# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0007_unit_model_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='model_pic',
        ),
        migrations.AddField(
            model_name='card',
            name='model_pic',
            field=models.ImageField(default='/static/armylist/no-img.jpg', upload_to='/static/armylist/'),
        ),
    ]
