# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0008_auto_20161107_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroupSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('armyParty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpellsParties', to='armylist.Army_Party')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelltroups', to='armylist.spell')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='controlemd5',
            field=models.CharField(default=datetime.datetime(2016, 11, 14, 14, 10, 21, 268000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='model_pic',
            field=models.ImageField(upload_to='armylist/cards'),
        ),
        migrations.AddField(
            model_name='army_party',
            name='spellList',
            field=models.ManyToManyField(related_name='spellParties', through='armylist.TroupSpell', to='armylist.spell'),
        ),
    ]
