# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0009_auto_20161114_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army_party',
            name='totalCost',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='army',
        ),
        migrations.AddField(
            model_name='card',
            name='army',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unitList', to='armylist.Army'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='controlemd5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to='armylist/cards'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
