# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0010_auto_20170524_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
