# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0011_auto_20170524_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='army',
        ),
        migrations.AddField(
            model_name='spell',
            name='army',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spellList', to='armylist.Army'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='army',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unitList', to='armylist.Army'),
            preserve_default=False,
        ),
    ]
