# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0013_unit_tir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
