# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0014_auto_20170524_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
