# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0017_auto_20170524_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='generique',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='type2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='vol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
