# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0018_auto_20170529_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack',
            old_name='cc',
            new_name='att',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='ct',
        ),
        migrations.AddField(
            model_name='attack',
            name='Effets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attack',
            name='type',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
