# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-30 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0019_auto_20170529_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competence',
            name='dim',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
