# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-30 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0020_auto_20170530_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='action',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='armure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitList', to='armylist.Army'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='commandment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='defence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='force',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='mouvement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='taille',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(blank=True, choices=[('Independant', 'Independant'), ('Unite', 'Unite'), ('Invocation', 'Invocation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='wound',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
