# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0021_auto_20170530_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
