# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-30 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0022_auto_20170530_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
