# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-30 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0023_auto_20170530_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='att',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='dmg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
