# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0024_auto_20170530_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='costSpell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
