# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0025_auto_20170601_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spellList', to='armylist.Army'),
        ),
    ]
