# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armylist', '0027_auto_20170728_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='resistance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
