# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-31 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('armylist', '0029_auto_20170731_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='army_list',
            field=models.ManyToManyField(related_name='Partys', to='armylist.Army_Party'),
        ),
        migrations.RemoveField(
            model_name='party',
            name='joueurs',
        ),
        migrations.AddField(
            model_name='party',
            name='joueurs',
            field=models.ManyToManyField(related_name='Partys', to=settings.AUTH_USER_MODEL),
        ),
    ]
